version: '3'
services:
  elasticsearch:
    container_name: rapidez_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    restart: unless-stopped
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - discovery.type=single-node
    ports:
      - 127.0.0.1:9200:9200
  magento:
    container_name: rapidez_magento
    image: michielgerritsen/magento-project-community-edition:php74-fpm-magento2.4.3-p1-sample-data
    restart: unless-stopped
    ports:
      - 127.0.0.1:1234:80
      - 127.0.0.1:3307:3306
    environment:
      - URL=http://localhost:1234/
      - FLAT_TABLES=true
  kibana:
    container_name: rapidez_kibana
    image: docker.elastic.co/kibana/kibana:7.6.0
    ports:
      - 127.0.0.1:5601:5601
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
