<?php

return [
    'catalog/frontend/flat_catalog_category'          => '0',
    'catalog/frontend/grid_per_page_values'           => '12,24,36',
    'catalog/frontend/flat_catalog_product'           => '0',
    'catalog/frontend/grid_per_page'                  => '12',
    'catalog/frontend/show_swatches_in_product_list'  => '1',
    'catalog/seo/category_url_suffix'                 => '.html',
    'catalog/seo/product_url_suffix'                  => '.html',
    'cataloginventory/item_options/backorders'        => '0',
    'cataloginventory/options/show_out_of_stock'      => '0',
    'checkout/cart/redirect_to_cart'                  => '0',
    'currency/options/default'                        => 'USD',
    'customer/address/company_show'                   => 'opt',
    'customer/address/fax_show'                       => '',
    'customer/address/middlename_show'                => '',
    'customer/address/prefix_options'                 => '',
    'customer/address/prefix_show'                    => '',
    'customer/address/street_lines'                   => '2',
    'customer/address/suffix_options'                 => '',
    'customer/address/suffix_show'                    => '',
    'customer/address/taxvat_show'                    => '',
    'customer/address/telephone_show'                 => 'req',
    'customer/create_account/vat_frontend_visibility' => '0',
    'design/search_engine_robots/default_robots'      => 'INDEX,FOLLOW',
    'general/country/default'                         => 'US',
    'general/locale/code'                             => 'en_US',
    'general/locale/timezone'                         => 'America/Los_Angeles',
    'general/region/display_all'                      => '0',
    'general/region/state_required'                   => '',
    'newsletter/general/active'                       => '1',
    'newsletter/subscription/allow_guest_subscribe'   => '1',
    'reports/options/enabled'                         => '0',
    'reports/options/product_view_enabled'            => '1',
    'tax/display/type'                                => '1',
    'trans_email/ident_general/email'                 => 'owner@example.com',
    'web/secure/base_url'                             => '{{unsecure_base_url}}',
    'web/url/catalog_media_url_format'                => 'hash',
    'customer/password/required_character_classes_number' => '3',
    'customer/password/minimum_password_length'       => '8',
];
