<?php
// The fully qualified class names of the models.
return [
    'page'                      => Rapidez\Core\Models\Page::class,
    'attribute'                 => Rapidez\Core\Models\Attribute::class,
    'product'                   => Rapidez\Core\Models\Product::class,
    'category'                  => Rapidez\Core\Models\Category::class,
    'config'                    => Rapidez\Core\Models\Config::class,
    'option_swatch'             => Rapidez\Core\Models\OptionSwatch::class,
    'option_value'              => Rapidez\Core\Models\OptionValue::class,
    'product_image'             => Rapidez\Core\Models\ProductImage::class,
    'product_view'              => Rapidez\Core\Models\ProductView::class,
    'product_option'            => Rapidez\Core\Models\ProductOption::class,
    'product_option_title'      => Rapidez\Core\Models\ProductOptionTitle::class,
    'product_option_price'      => Rapidez\Core\Models\ProductOptionPrice::class,
    'product_option_type_title' => Rapidez\Core\Models\ProductOptionTypeTitle::class,
    'product_option_type_price' => Rapidez\Core\Models\ProductOptionTypePrice::class,
    'product_option_type_value' => Rapidez\Core\Models\ProductOptionTypeValue::class,
    'quote'                     => Rapidez\Core\Models\Quote::class,
    'quote_item'                => Rapidez\Core\Models\QuoteItem::class,
    'quote_item_option'         => Rapidez\Core\Models\QuoteItemOption::class,
    'rewrite'                   => Rapidez\Core\Models\Rewrite::class,
    'store'                     => Rapidez\Core\Models\Store::class,
    'widget'                    => Rapidez\Core\Models\Widget::class,
    'block'                     => Rapidez\Core\Models\Block::class,
    'sales_order'               => Rapidez\Core\Models\SalesOrder::class,
    'sales_order_address'       => Rapidez\Core\Models\SalesOrderAddress::class,
    'sales_order_item'          => Rapidez\Core\Models\SalesOrderItem::class,
    'sales_order_payment'       => Rapidez\Core\Models\SalesOrderPayment::class,
];
