<?php

// The fully qualified class names of the models.
return [
    'attribute'                 => Rapidez\Core\Models\Attribute::class,
    'attribute_option'          => Rapidez\Core\Models\AttributeOption::class,
    'attribute_datetime'        => Rapidez\Core\Models\AttributeDatetime::class,
    'attribute_decimal'         => Rapidez\Core\Models\AttributeDecimal::class,
    'attribute_int'             => Rapidez\Core\Models\AttributeInt::class,
    'attribute_text'            => Rapidez\Core\Models\AttributeText::class,
    'attribute_varchar'         => Rapidez\Core\Models\AttributeVarchar::class,
    'block'                     => Rapidez\Core\Models\Block::class,
    'category'                  => Rapidez\Core\Models\Category::class,
    'category_product'          => Rapidez\Core\Models\CategoryProduct::class,
    'customer'                  => Rapidez\Core\Models\Customer::class,
    'customer_group'            => Rapidez\Core\Models\CustomerGroup::class,
    'config'                    => Rapidez\Core\Models\Config::class,
    'oauth_token'               => Rapidez\Core\Models\OauthToken::class,
    'option_swatch'             => Rapidez\Core\Models\OptionSwatch::class,
    'option_value'              => Rapidez\Core\Models\OptionValue::class,
    'page'                      => Rapidez\Core\Models\Page::class,
    'product'                   => Rapidez\Core\Models\Product::class,
    'product_image'             => Rapidez\Core\Models\ProductImage::class,
    'product_image_value'       => Rapidez\Core\Models\ProductImageValue::class,
    'product_link'              => Rapidez\Core\Models\ProductLink::class,
    'product_option'            => Rapidez\Core\Models\ProductOption::class,
    'product_option_price'      => Rapidez\Core\Models\ProductOptionPrice::class,
    'product_option_title'      => Rapidez\Core\Models\ProductOptionTitle::class,
    'product_option_type_price' => Rapidez\Core\Models\ProductOptionTypePrice::class,
    'product_option_type_title' => Rapidez\Core\Models\ProductOptionTypeTitle::class,
    'product_option_type_value' => Rapidez\Core\Models\ProductOptionTypeValue::class,
    'product_price'             => Rapidez\Core\Models\ProductPrice::class,
    // TODO: the naming is mixed..
    'product_review'         => Rapidez\Core\Models\Review::class,
    'product_review_summary' => Rapidez\Core\Models\ProductReviewSummary::class,
    'product_stock'          => Rapidez\Core\Models\ProductStock::class,
    'product_super_link'     => Rapidez\Core\Models\ProductSuperLink::class,
    'product_tier_price'     => Rapidez\Core\Models\ProductTierPrice::class,
    'product_view'           => Rapidez\Core\Models\ProductView::class,
    'quote'                  => Rapidez\Core\Models\Quote::class,
    'quote_id_mask'          => Rapidez\Core\Models\QuoteIdMask::class,
    'quote_item'             => Rapidez\Core\Models\QuoteItem::class,
    'quote_item_option'      => Rapidez\Core\Models\QuoteItemOption::class,
    'report_event'           => Rapidez\Core\Models\ReportEvent::class,
    'rewrite'                => Rapidez\Core\Models\Rewrite::class,
    'sales_order'            => Rapidez\Core\Models\SalesOrder::class,
    'sales_order_address'    => Rapidez\Core\Models\SalesOrderAddress::class,
    'sales_order_item'       => Rapidez\Core\Models\SalesOrderItem::class,
    'sales_order_payment'    => Rapidez\Core\Models\SalesOrderPayment::class,
    'search_query'           => Rapidez\Core\Models\SearchQuery::class,
    'search_synonym'         => Rapidez\Core\Models\SearchSynonym::class,
    'store'                  => Rapidez\Core\Models\Store::class,
    'super_attribute'        => Rapidez\Core\Models\SuperAttribute::class,
    'widget'                 => Rapidez\Core\Models\Widget::class,
];
