name: Check translations

on:
  push:
    branches:
      - master
      - '*.x'
  pull_request:

jobs:
  translations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none
      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction
      - name: Check translations
        uses: rapidez/laravel-translation-checker@1.0.0
